version: "3"

services:
  knowledge-collaboratory-api:
    container_name: knowledge-collaboratory-api
    build: .
    restart: unless-stopped
    # command: src/api.py
    # ports:
    #   - 8808:8808
    environment: 
      # Variable for nginx-proxy routing. See https://github.com/nginx-proxy/
      TRAPI_DATA_DIR: /data
      # VIRTUAL_HOST: nanopub-kgx-api.137.120.31.102.nip.io
      # LETSENCRYPT_HOST: nanopub-kgx-api.137.120.31.102.nip.io
      VIRTUAL_HOST: api.collaboratory.semanticscience.org
      LETSENCRYPT_HOST: api.collaboratory.semanticscience.org
      VIRTUAL_PORT: 8808
      ## To implement (see kgx_transformer.py)
      # ENDPOINT: http://virtuoso.np.dumontierlab.137.120.31.101.nip.io/sparql
    volumes:
      - /data/nanopub-kgx-api:/data

  # comunica-sparql-endpoint:
  #   container_name: nanopub-sparql
  #   image: comunica/actor-init-sparql:latest
  #   # image: comunica/actor-init-sparql:1.18.1
  #   # Comunica is not supported by RDF4J:
  #   # https://github.com/comunica/comunica/issues/762
  #   restart: unless-stopped
  #   # entrypoint: comunica-sparql-http http://ldf.nanopubs.lod.labs.vu.nl/np
  #   entrypoint: node ./bin/http.js http://ldf.np.dumontierlab.com/np
  #   ports:
  #     - 3000:3000
  #   environment: 
  #     # Variable for nginx-proxy routing. See https://github.com/nginx-proxy/
  #     VIRTUAL_HOST: nanopub-sparql.137.120.31.102.nip.io
  #     # LETSENCRYPT_HOST: nanopub-sparql.137.120.31.102.nip.io
  #     VIRTUAL_PORT: 3000
  #     NODE_OPTIONS: --max_old_space_size=16384
  #   networks:
  #     - network

  # sparql-reasoner-api:
  #   container_name: d2s-api-nanopub
  #   image: umids/d2s-api:nanopubs
  #   # ports:
  #   #   - 8081:8080
  #   environment: 
  #     # - ENDPOINT=nanopub-sparql.137.120.31.102.nip.io
  #     # - ENDPOINT=http://comunica-sparql-endpoint:3000/sparql
  #     - ENDPOINT=http://virtuoso.np.dumontierlab.137.120.31.101.nip.io/sparql
  #     - VIRTUAL_HOST=nanopub-reasoner-api.137.120.31.102.nip.io
  #     # - LETSENCRYPT_HOST=nanopub-reasoner-api.137.120.31.102.nip.io
  #   networks:
  #     - network
  #   restart: unless-stopped

networks:
  network:
    driver: bridge
