version: "3"

services:
  nanopub-reasoner-api:
    container_name: nanopub-reasoner-api
    build: .
    restart: unless-stopped
    # command: src/api.py
    ports:
      - 8808:8808
    environment: 
      # Variable for nginx-proxy routing. See https://github.com/nginx-proxy/
      VIRTUAL_HOST: nanopub-reasoner-api.137.120.31.102.nip.io
      LETSENCRYPT_HOST: nanopub-reasoner-api.137.120.31.102.nip.io
      VIRTUAL_PORT: 8808
    # volumes:
    #   - ./data:/data
