version: "3"
services:

  api:
    # container_name: knowledge-collaboratory-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    ports:
      - 8808:8808
    volumes:
      - ./src:/app/src
      # - /data/nanopub-kgx-api:/data
    environment:
      # Show print() in logs:
      PYTHONUNBUFFERED: '1'
      DEV_MODE: 'true'

    entrypoint: uvicorn src.main:app --host 0.0.0.0 --port 8808 --reload
    ## Gunicorn for multiple uvicorn workers in prod:
    # entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8808 openpredict.main:app



  # comunica-sparql-endpoint:
  #   container_name: nanopub-sparql
  #   image: comunica/actor-init-sparql:latest
  #   # image: comunica/actor-init-sparql:1.18.1
  #   # Comunica is not supported by RDF4J:
  #   # https://github.com/comunica/comunica/issues/762
  #   restart: unless-stopped
  #   # entrypoint: comunica-sparql-http http://ldf.nanopubs.lod.labs.vu.nl/np
  #   entrypoint: node ./bin/http.js http://ldf.np.dumontierlab.com/np
  #   ports:
  #     - 3000:3000
  #   environment: 
  #     # Variable for nginx-proxy routing. See https://github.com/nginx-proxy/
  #     VIRTUAL_HOST: nanopub-sparql.137.120.31.102.nip.io
  #     # LETSENCRYPT_HOST: nanopub-sparql.137.120.31.102.nip.io
  #     VIRTUAL_PORT: 3000
  #     NODE_OPTIONS: --max_old_space_size=16384
  #   networks:
  #     - network

  # sparql-reasoner-api:
  #   container_name: d2s-api-nanopub
  #   image: umids/d2s-api:nanopubs
  #   # ports:
  #   #   - 8081:8080
  #   environment: 
  #     # - ENDPOINT=nanopub-sparql.137.120.31.102.nip.io
  #     # - ENDPOINT=http://comunica-sparql-endpoint:3000/sparql
  #     - ENDPOINT=http://virtuoso.np.dumontierlab.137.120.31.101.nip.io/sparql
  #     - VIRTUAL_HOST=nanopub-reasoner-api.137.120.31.102.nip.io
  #     # - LETSENCRYPT_HOST=nanopub-reasoner-api.137.120.31.102.nip.io
  #   networks:
  #     - network
  #   restart: unless-stopped