version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    environment: 
      # Variable for nginx-proxy routing. See https://github.com/nginx-proxy
      VIRTUAL_HOST: api.collaboratory.semanticscience.org
      LETSENCRYPT_HOST: api.collaboratory.semanticscience.org
      VIRTUAL_PORT: 8808

    # entrypoint: pytest tests/integration/test_trapi.py::test_post_trapi -s
    entrypoint: pytest tests/production/test_production_api.py::test_post_trapi -s
