PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX bl: <https://w3id.org/biolink/vocab/>
PREFIX d2s: <https://w3id.org/d2s/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX bio2rdf: <http://bio2rdf.org/>
PREFIX covid: <http://idlab.github.io/covid19#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dctypes: <http://purl.org/dc/dcmitype/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX idot: <http://identifiers.org/idot/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX void-ext: <http://ldf.fi/void-ext#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX schema: <http://schema.org/>
PREFIX omop: <http://api.ohdsi.org/WebAPI/vocabulary/concept/>
PREFIX cohd: <https://w3id.org/trek/cohd/>
CONSTRUCT {
  ?association
    bl:association_type ?association_type ;
    rdfs:label ?label ;
    rdf:subject ?subject ;
    rdf:predicate ?predicate ;
    rdf:object ?object ;
    bl:relation ?relation ;
  	bl:provided_by ?provided_by ;
    bl:has_evidence ?targetgroup ;
    bl:stage_qualifier ?lifestage .
  
  ?subject bl:category ?subjectCategory .
  ?object bl:category ?objectCategory . 

  ?targetgroup a ?targetGroupType ;
    bl:category ?targetGroupCategory ;
    bl:has_drug ?drug ;
    bl:has_phenotype ?phenotype .
  ?lifestage a bl:LifeStage ;
    rdfs:label ?lifestageLabel .
}
WHERE { 
  ?association
    bl:association_type ?association_type ;
    rdf:subject ?subject ;
    rdf:predicate ?predicate ;
    rdf:object ?object ;
    bl:relation ?relation ;
  	bl:provided_by ?provided_by .
  
  ?subject bl:category ?subjectCategory .
  ?object bl:category ?objectCategory . 

  OPTIONAL {
    ?association rdfs:label ?label .
  }
  
  OPTIONAL {
    ?association bl:has_evidence ?targetgroup .
    ?targetgroup a ?targetGroupType ;
      bl:category ?targetGroupCategory .
	}
  OPTIONAL {
    ?targetgroup bl:has_drug ?drug .
	}
  OPTIONAL {
    ?targetgroup bl:has_phenotype ?phenotype .
	}  
  OPTIONAL {
    ?association bl:stage_qualifier ?lifestage .
    ?lifestage a bl:LifeStage ;
      rdfs:label ?lifestageLabel .
	}
}
