name: Run tests
# Run test at each push to master
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - 'requirements.txt'
    - 'src/**'
    - 'tests/**'
    - '.github/workflows/run-tests.yml'

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        # python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install .

    - name: Test
      run: pytest tests/integration/*

